name: buildTestingMacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - name: Cloning Git repository
        uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - name: Attempt to build the Live Enhancement Suite for macOS
        run: |
          export XCODE_ARGS="build build-for-testing GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES"
          xcodebuild -workspace Hammerspoon.xcworkspace -scheme Release ${XCODE_ARGS}
      - name: Copy Hammerspoon binary to root for disk image packaging
        run: |
          mkdir release
          cp -Rv /Users/runner/Library/Developer/Xcode/DerivedData/*/Build/Products/Release/*.app/ ./Live\ Enhancement\ Suite.app/
      - name: Set up environment for disk image creation
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Create Live Enhancement Suite disk image
        run: |
          npm install -g create-dmg
          create-dmg Live\ Enhancement\ Suite.app release 2>&1 || true
          mv release/*.dmg release/Live\ Enhancement\ Suite.dmg
          shasum release/*.dmg >> release/CHECKSUM_SHA256.txt
      - name: Upload disk image and image checksum as artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: 'Disk Image'
          path: release/
