name: ReleaseGithubAction

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - name: Cloning Git repository
        uses: actions/checkout@v1
        with:
          submodules: 'recursive'
      - name: Attempt to build the Live Enhancement Suite for macOS
        run: |
          export XCODE_ARGS="build build-for-testing GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES"
          xcodebuild -workspace Hammerspoon.xcworkspace -scheme Release ${XCODE_ARGS}
      - name: Copy Hammerspoon binary to root for disk image packaging
        run: |
          mkdir release
          cp -Rv /Users/runner/Library/Developer/Xcode/DerivedData/*/Build/Products/Release/*.app/ ./Live\ Enhancement\ Suite.app/
      - name: Set up environment for disk image creation
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Create Live Enhancement Suite disk image
        run: |
          npm install -g create-dmg
          create-dmg --dmg-title="Live Enhancement Suite" Live\ Enhancement\ Suite.app release 2>&1 || true
          mv release/*.dmg release/LiveEnhancementSuite.dmg
          shasum release/*.dmg >> release/CHECKSUM_SHA256.txt
      - name: Upload disk image as release asset
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/LiveEnhancementSuite.dmg
          asset_name: LiveEnhancementSuite.dmg
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload checksum as release asset
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/CHECKSUM_SHA256.txt
          asset_name: CHECKSUM_SHA256.txt
          tag: ${{ github.ref }}
          overwrite: true
